=== Amsterdam/signals-frontend/environment.conf.schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$ref": "#/definitions/Test",
    "definitions": {
        "Test": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "head": {
                    "$ref": "#/definitions/Head"
                },
                "logo": {
                    "$ref": "#/definitions/Logo"
                },
                "sentry": {
                    "$ref": "#/definitions/Sentry"
                },
                "matomo": {
                    "$ref": "#/definitions/Matomo"
                },
                "language": {
                    "$ref": "#/definitions/Language"
                },
                "links": {
                    "$ref": "#/definitions/Links"
                },
                "theme": {
                    "$ref": "#/definitions/Theme"
                },
                "map": {
                    "$ref": "#/definitions/Map"
                },
                "fetchQuestionsFromBackend": {
                    "type": "boolean"
                },
                "showVulaanControls": {
                    "type": "boolean"
                },
                "STATIC_MAP_SERVER_URL": {
                    "type": "string",
                    "format": "uri"
                },
                "AUTH_ME_ENDPOINT": {
                    "type": "string",
                    "format": "uri"
                },
                "CATEGORIES_ENDPOINT": {
                    "type": "string",
                    "format": "uri"
                },
                "CATEGORIES_PRIVATE_ENDPOINT": {
                    "type": "string",
                    "format": "uri"
                },
                "DEPARTMENTS_ENDPOINT": {
                    "type": "string",
                    "format": "uri"
                },
                "FEEDBACK_FORMS_ENDPOINT": {
                    "type": "string",
                    "format": "uri"
                },
                "FEEDBACK_STANDARD_ANSWERS_ENDPOINT": {
                    "type": "string",
                    "format": "uri"
                },
                "FILTERS_ENDPOINT": {
                    "type": "string",
                    "format": "uri"
                },
                "GEOGRAPHY_ENDPOINT": {
                    "type": "string",
                    "format": "uri"
                },
                "IMAGE_ENDPOINT": {
                    "type": "string",
                    "format": "uri"
                },
                "INCIDENTS_ENDPOINT": {
                    "type": "string",
                    "format": "uri"
                },
                "INCIDENT_PRIVATE_ENDPOINT": {
                    "type": "string",
                    "format": "uri"
                },
                "INCIDENT_PUBLIC_ENDPOINT": {
                    "type": "string",
                    "format": "uri"
                },
                "OIDC_AUTH_ENDPOINT": {
                    "type": "string",
                    "format": "uri"
                },
                "OIDC_CLIENT_ID": {
                    "type": "string"
                },
                "OIDC_RESPONSE_TYPE": {
                    "type": "string"
                },
                "OIDC_SCOPE": {
                    "type": "string"
                },
                "OVL_KLOKKEN_LAYER": {
                    "type": "string",
                    "format": "uri"
                },
                "OVL_VERLICHTING_LAYER": {
                    "type": "string",
                    "format": "uri"
                },
                "PERMISSIONS_ENDPOINT": {
                    "type": "string",
                    "format": "uri"
                },
                "PREDICTION_ENDPOINT": {
                    "type": "string",
                    "format": "uri"
                },
                "QUESTIONS_ENDPOINT": {
                    "type": "string",
                    "format": "uri"
                },
                "ROLES_ENDPOINT": {
                    "type": "string",
                    "format": "uri"
                },
                "SEARCH_ENDPOINT": {
                    "type": "string",
                    "format": "uri"
                },
                "TERMS_ENDPOINT": {
                    "type": "string",
                    "format": "uri"
                },
                "USERS_ENDPOINT": {
                    "type": "string",
                    "format": "uri"
                }
            },
            "required": [
                "AUTH_ME_ENDPOINT",
                "CATEGORIES_ENDPOINT",
                "CATEGORIES_PRIVATE_ENDPOINT",
                "DEPARTMENTS_ENDPOINT",
                "FEEDBACK_FORMS_ENDPOINT",
                "FEEDBACK_STANDARD_ANSWERS_ENDPOINT",
                "FILTERS_ENDPOINT",
                "GEOGRAPHY_ENDPOINT",
                "IMAGE_ENDPOINT",
                "INCIDENTS_ENDPOINT",
                "INCIDENT_PRIVATE_ENDPOINT",
                "INCIDENT_PUBLIC_ENDPOINT",
                "OIDC_AUTH_ENDPOINT",
                "OIDC_CLIENT_ID",
                "OIDC_RESPONSE_TYPE",
                "OIDC_SCOPE",
                "OVL_KLOKKEN_LAYER",
                "OVL_VERLICHTING_LAYER",
                "PERMISSIONS_ENDPOINT",
                "PREDICTION_ENDPOINT",
                "QUESTIONS_ENDPOINT",
                "ROLES_ENDPOINT",
                "SEARCH_ENDPOINT",
                "STATIC_MAP_SERVER_URL",
                "TERMS_ENDPOINT",
                "USERS_ENDPOINT",
                "fetchQuestionsFromBackend",
                "head",
                "language",
                "links",
                "logo",
                "map",
                "matomo",
                "sentry",
                "showVulaanControls",
                "theme"
            ],
            "title": "Test"
        },
        "Head": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "androidIcon": {
                    "type": "string"
                },
                "backgroundColor": {
                    "type": "string"
                },
                "favicon": {
                    "type": "string"
                },
                "iosIcon": {
                    "type": "string"
                },
                "statusBarStyle": {
                    "type": "string"
                },
                "themeColor": {
                    "type": "string"
                }
            },
            "required": [
                "androidIcon",
                "backgroundColor",
                "favicon",
                "iosIcon",
                "statusBarStyle",
                "themeColor"
            ],
            "title": "Head"
        },
        "Language": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "avgDisclaimer": {
                    "type": "string"
                },
                "consentToContactSharing": {
                    "type": "string"
                },
                "footer1": {
                    "type": "string"
                },
                "footer2": {
                    "type": "string"
                },
                "headerTitle": {
                    "type": "string"
                },
                "phoneNumber": {
                    "type": "string"
                },
                "shortTitle": {
                    "type": "string"
                },
                "siteTitle": {
                    "type": "string"
                },
                "smallHeaderTitle": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "urgentContactInfo": {
                    "type": "string"
                }
            },
            "required": [
                "avgDisclaimer",
                "consentToContactSharing",
                "footer1",
                "footer2",
                "headerTitle",
                "phoneNumber",
                "shortTitle",
                "siteTitle",
                "smallHeaderTitle",
                "title",
                "urgentContactInfo"
            ],
            "title": "Language"
        },
        "Links": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "help": {
                    "type": "string",
                    "format": "uri"
                },
                "home": {
                    "type": "string",
                    "format": "uri"
                },
                "privacy": {
                    "type": "string",
                    "format": "uri"
                }
            },
            "required": [
                "help",
                "home",
                "privacy"
            ],
            "title": "Links"
        },
        "Logo": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "url": {
                    "type": "null"
                },
                "width": {
                    "type": "integer"
                },
                "height": {
                    "type": "integer"
                },
                "smallWidth": {
                    "type": "integer"
                },
                "smallHeight": {
                    "type": "integer"
                }
            },
            "required": [
                "height",
                "smallHeight",
                "smallWidth",
                "url",
                "width"
            ],
            "title": "Logo"
        },
        "Map": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "municipality": {
                    "type": "string"
                },
                "options": {
                    "$ref": "#/definitions/MapOptions"
                },
                "optionsBackOffice": {
                    "$ref": "#/definitions/OptionsBackOffice"
                },
                "tiles": {
                    "$ref": "#/definitions/Tiles"
                }
            },
            "required": [
                "municipality",
                "options",
                "optionsBackOffice",
                "tiles"
            ],
            "title": "Map"
        },
        "MapOptions": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "center": {
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                },
                "maxBounds": {
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items": {
                            "type": "number"
                        }
                    }
                },
                "maxZoom": {
                    "type": "integer"
                },
                "minZoom": {
                    "type": "integer"
                },
                "zoom": {
                    "type": "integer"
                }
            },
            "required": [
                "center",
                "maxBounds",
                "maxZoom",
                "minZoom",
                "zoom"
            ],
            "title": "MapOptions"
        },
        "OptionsBackOffice": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "maxZoom": {
                    "type": "integer"
                },
                "minZoom": {
                    "type": "integer"
                },
                "zoom": {
                    "type": "integer"
                }
            },
            "required": [
                "maxZoom",
                "minZoom",
                "zoom"
            ],
            "title": "OptionsBackOffice"
        },
        "Tiles": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "args": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "options": {
                    "$ref": "#/definitions/TilesOptions"
                }
            },
            "required": [
                "args",
                "options"
            ],
            "title": "Tiles"
        },
        "TilesOptions": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "attribution": {
                    "type": "string"
                },
                "subdomains": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "tms": {
                    "type": "boolean"
                }
            },
            "required": [
                "attribution",
                "subdomains",
                "tms"
            ],
            "title": "TilesOptions"
        },
        "Matomo": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "urlBase": {
                    "type": "string",
                    "format": "uri"
                },
                "siteId": {
                    "type": "integer"
                }
            },
            "required": [
                "siteId",
                "urlBase"
            ],
            "title": "Matomo"
        },
        "Sentry": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "dsn": {
                    "type": "string",
                    "format": "uri"
                }
            },
            "required": [
                "dsn"
            ],
            "title": "Sentry"
        },
        "Theme": {
            "type": "object",
            "additionalProperties": false,
            "title": "Theme"
        }
    }
}

=== Amsterdam/signals-frontend/environment.conf.e2e.json
{
  "head": {
    "androidIcon": "/icon_192x192.png",
    "backgroundColor": "#ffffff",
    "favicon": "/favicon.png",
    "iosIcon": "/icon_180x180.png",
    "statusBarStyle": "default",
    "themeColor": "#ec0000"
  },
  "logo": {
    "url": null,
    "width": 0,
    "height": 0,
    "smallWidth": 0,
    "smallHeight": 0
  },
  "sentry": {
    "dsn": "https://3de59e3a93034a348089131aa565bdf4@sentry.data.amsterdam.nl/27"
  },
  "matomo": {
    "urlBase": "https://analytics.data.amsterdam.nl/",
    "siteId": 14
  },
  "language": {
    "avgDisclaimer": "De gemeente Amsterdam verwerkt uw persoonsgegevens op een zorgvuldige en veilige manier in overeenstemming met de geldende wet- en regelgeving, waaronder de Algemene Verordening Gegevensbescherming. Lees meer hierover op <a href='##AVG_DISCLAIMER_URL##'>Privacyverklaring Meldingen openbare ruimte en overlast</a>.",
    "consentToContactSharing": "Ja, ik geef de gemeente Amsterdam toestemming om mijn contactgegevens te delen met andere organisaties, als dat nodig is om mijn melding goed op te lossen.",
    "footer1": "Bel het Gemeentelijk informatienummer: <a href='tel:##GENERAL_PHONE_NUMBER_FORMATTED##'>##GENERAL_PHONE_NUMBER##</a>",
    "footer2": "op werkdagen van 08.00 tot 18.00 uur.",
    "headerTitle": "",
    "phoneNumber": "14 020",
    "shortTitle": "SIA",
    "siteTitle": "SIA - Signalen Informatievoorziening Amsterdam",
    "smallHeaderTitle": "SIA",
    "title": "Signalen Informatievoorziening Amsterdam",
    "urgentContactInfo": "Voor spoedeisende zaken kunt u ook telefonisch contact opnemen met 14 020."
  },
  "links": {
    "help": "https://tamtam.amsterdam.nl/do/office?id=1723860-6f6666696365",
    "home": "https://www.amsterdam.nl",
    "privacy": "https://www.amsterdam.nl/privacy/specifieke/privacyverklaringen-wonen/meldingen-overlast-privacy/"
  },
  "theme": {},
  "map": {
    "municipality": "amsterdam",
    "options": {
      "center": [
        52.3731081,
        4.8932945
      ],
      "maxBounds": [
        [
          52.25168,
          4.64034
        ],
        [
          52.50536,
          5.10737
        ]
      ],
      "maxZoom": 14,
      "minZoom": 8,
      "zoom": 10
    },
    "optionsBackOffice": {
      "maxZoom": 16,
      "minZoom": 7,
      "zoom": 7
    },
    "tiles": {
      "args": [
        "https://{s}.data.amsterdam.nl/topo_rd/{z}/{x}/{y}.png"
      ],
      "options": {
        "attribution": "Kaartgegevens CC-BY-4.0 Gemeente Amsterdam",
        "subdomains": [
          "t1",
          "t2",
          "t3",
          "t4"
        ],
        "tms": true
      }
    }
  },
  "fetchQuestionsFromBackend": false,
  "showVulaanControls": true,
  "STATIC_MAP_SERVER_URL": "https://map.data.amsterdam.nl/maps/topografie",
  "AUTH_ME_ENDPOINT": "http://localhost:8000/signals/v1/private/me/",
  "CATEGORIES_ENDPOINT": "http://localhost:8000/signals/v1/public/terms/categories/",
  "CATEGORIES_PRIVATE_ENDPOINT": "http://localhost:8000/signals/v1/private/categories/",
  "DEPARTMENTS_ENDPOINT": "http://localhost:8000/signals/v1/private/departments/",
  "FEEDBACK_FORMS_ENDPOINT": "http://localhost:8000/signals/v1/public/feedback/forms/",
  "FEEDBACK_STANDARD_ANSWERS_ENDPOINT": "http://localhost:8000/signals/v1/public/feedback/standard_answers/",
  "FILTERS_ENDPOINT": "http://localhost:8000/signals/v1/private/me/filters/",
  "GEOGRAPHY_ENDPOINT": "http://localhost:8000/signals/v1/private/signals/geography",
  "IMAGE_ENDPOINT": "http://localhost:8000/signals/signal/image/",
  "INCIDENTS_ENDPOINT": "http://localhost:8000/signals/v1/private/signals/",
  "INCIDENT_PRIVATE_ENDPOINT": "http://localhost:8000/signals/v1/private/signals/",
  "INCIDENT_PUBLIC_ENDPOINT": "http://localhost:8000/signals/v1/public/signals/",
  "OIDC_AUTH_ENDPOINT": "http://localhost:5556/auth",
  "OIDC_CLIENT_ID": "signals",
  "OIDC_RESPONSE_TYPE": "id_token",
  "OIDC_SCOPE": "openid email profile",
  "OVL_KLOKKEN_LAYER": "https://map.data.amsterdam.nl/maps/openbare_verlichting?REQUEST=GetFeature&SERVICE=wfs&OUTPUTFORMAT=application/json;%20subtype=geojson;%20charset=utf-8&Typename=Klokken&version=1.1.0&srsname=urn:ogc:def:crs:EPSG::4326",
  "OVL_VERLICHTING_LAYER": "https://map.data.amsterdam.nl/maps/openbare_verlichting?REQUEST=GetFeature&SERVICE=wfs&OUTPUTFORMAT=application/json;%20subtype=geojson;%20charset=utf-8&Typename=Verlichting&version=1.1.0&srsname=urn:ogc:def:crs:EPSG::4326",
  "PERMISSIONS_ENDPOINT": "http://localhost:8000/signals/v1/private/permissions/",
  "PREDICTION_ENDPOINT": "http://localhost:8000/signals/category/prediction",
  "QUESTIONS_ENDPOINT": "http://localhost:8000/signals/v1/public/questions/",
  "ROLES_ENDPOINT": "http://localhost:8000/signals/v1/private/roles/",
  "SEARCH_ENDPOINT": "http://localhost:8000/signals/v1/private/search",
  "TERMS_ENDPOINT": "http://localhost:8000/signals/v1/private/terms/categories/",
  "USERS_ENDPOINT": "http://localhost:8000/signals/v1/private/users/"
}
